import Head from "next/head";

import { Main } from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Socket-io simple</title>
        <meta content="Generated by create next app" name="description" />
      </Head>

      <Main />
    </>
  );
}
