import Head from "next/head";

import { Main, Navbar } from "../components";
import { useStore } from "../hooks";

export default function Home() {
  const user = useStore((state) => state.user);
  return (
    <>
      <Head>
        <title>Socket-io simple</title>
        <meta content="Generated by create next app" name="description" />
      </Head>

      {user && <Navbar />}

      <Main />
    </>
  );
}
